ng generate component 404.html
ng generate component about-us.html
ng generate component add-cart.html
ng generate component blog-masonry.html
ng generate component blog-q.html
ng generate component category-grid.html
ng generate component category-listview.html
ng generate component checkout-q.html
ng generate component coming-soon.html
ng generate component contact-us.html
ng generate component create-account.html
ng generate component customer-profile.html
ng generate component delivery-shipping.html
ng generate component faq-q.html
ng generate component index.html
ng generate component order-placed.html
ng generate component product-detail.html
ng generate component product-detail1.html
ng generate component product-detail2.html
ng generate component product-detail3.html
ng generate component product-list.html
ng generate component product.html
ng generate component reset-password.html
ng generate component return-and-exchange.html
ng generate component sale.html
ng generate component search-page-grid.html
ng generate component search-page.html
ng generate component sell-on-quicentro.html
ng generate component single.html
ng generate component terms-conditions.html
ng generate component today-deals.html
ng generate component track-order.html
ng generate component vendor-details.html
ng generate component vendor-registration.html
ng generate component wishlist-q.html
